---
title: "novelty_infographic"
output: html_document
---

```{r}
pacman::p_load(tidyverse, ggridges, patchwork)


```

# Jitter values
```{r}
jitter_values <- function(x, prob=0.2){
  flip <- runif(1)
  
  if (flip > prob){
    return(x)
  }
  
  if (x == 1){
    return(x+1)
  }
  if (x== 4){
    return(x-1)
  }
  else{
    dir <- runif(1)
    if (dir > 0.5){
      return(x+1)
    }
    return(x-1)
  }
}

vect_jitter_values <- Vectorize(jitter_values)
```


# Hard code bins and hack ggridges
```{r}

# rep the values from 1-4 instead
t1_length <- 4
t2_length <- 3
t3_length <- 3

t1 <- c(
  rep(1, 20),
  rep(2, 60),
  rep(3, 20),
  rep(4, 20)
)

t2 <- c(
  rep(1, 30),
  rep(2, 20),
  rep(3, 20),
  rep(4, 50)
)

t3 <- c(
  rep(1, 30),
  rep(2, 20),
  rep(3, 40),
  rep(4, 30)
)


n_bins <- length(t1)

df <- tibble(
  vals = c(
    rep(t1, t1_length),
    rep(t2, t2_length),
    rep(t3, t3_length)
  ),
#  labs = c(
#    rep(c("Phobia", "Anxiety", "Obsessions", "Avoidance"), each=4, times=10)
#  ),
  time = c(
    rep(1:10, each=n_bins)
  ),
  novelty = c(
    rep(NA, n_bins),
    rep(NA, n_bins), 
    rep(1, n_bins), 
    rep(1, n_bins), 
    rep(4, n_bins),  
    rep(2.5, n_bins), 
    rep(1.1, n_bins), 
    rep(3.4, n_bins), 
    rep(2.3, n_bins), 
    rep(1, n_bins)
  )
)

plot_colors <- c("grey", "#fcffa4", "#f98e09", "#bc3754")

ridge_theme <- theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())


ridge_p <-df %>% 
  mutate(vals = vect_jitter_values(vals)) %>% 
  ggplot(aes(x=vals, 
             y=fct_rev(as.factor(time)), 
             height=stat(density),
             fill = novelty)) +
  geom_density_ridges2(stat="binline", bins=7, scale=0.8, draw_baseline=F) +
  scale_x_continuous(breaks = seq(1,4), labels = c("Phobia", "Anxiety", "Obsessions", "Avoidance")) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position="right",
        axis.text.x = element_text(angle=45)) +
  labs(x = "Keyword", y = "Time", fill = "Novelty") +
  scale_fill_continuous(breaks=c(1,2.5,4), labels=c("Low", "Medium", "High"), type="viridis", direction=-1)


novelty_p <- df %>% 
  ggplot(aes(x = -time, y = novelty)) +
  geom_line() +
  coord_flip() +
  ridge_theme +
  labs(x = "", y= "Novelty") +
  scale_y_continuous(breaks = c(1, 2.5, 4), labels=c("Low", "Medium", "High")) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.y = element_blank())


ridge_p + novelty_p + plot_layout(widths = c(2,1), guides="collect") + plot_annotation(tag_levels="a")

# remove colors from ridge_p ?
# hardcode some minor differences in the different time steps


```



